<?php

  function simple_contact_form_alter(&$form, &$form_state, $form_id) {
    print_r($form_id);
    if ($form_id == 'contact_site_form') {
      print '<pre>';
      print_r($form);
      print '</pre>';
      //display author and date info checkbox to 0 (unchecked)
      //hide the send yourself a copy checkbox
      $form['copy']['#access'] = 0;
      $form['copy']['#default_value'] = 1;
      $form['subject']['#access'] = 0;
      $form['subject']['#title'] = "Feedback";
    }
  }
